name: AHK CI Build

on: 
  workflow_dispatch:

jobs:
  Build_Release:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: fh_bot.ahk
          icon: fh.ico

      - name: Zip
        uses: vimtor/action-zip@v1.2
        with:
          files: |
              fh_bot.exe
              ./how_to.txt
          dest: fhbot.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: FH BOT
          tag_name: fhbot 
          body: |
              >[!NOTE]
              >**This release was built by Github Actions**
              >| [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) |
              >| ------------- |

          files: fhbot.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
